version: "3.8"
services:
  frontend:
    container_name: planet_frontend
    build: frontend
    image: htrvolker/planets-frontend:latest
    ports:
    - target: 80
      published: 80
    environment:
      BACKEND_HOSTNAME: planet_backend
  
  backend:
    container_name: planet_backend
    build: backend
    image: htrvolker/planets-backend:latest
    ports:
    - target: 80
      published: 8080
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    depends_on:
    - database
  
  database:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: planets
