pipeline {
    environment {
        CREATE_SCHEMA = "true"
        DATABASE_URI = "sqlite:///"
    }
    stages {
        stage('Setup') {
            sh 'jenkins/scripts/setup.sh'
        }
        stage('Test') {
            sh 'jenkins/scripts/test.sh'
        }
    }
}
