pipeline {
    agent any
    environment {
        CREATE_SCHEMA = "true"
        DATABASE_URI = "sqlite:///"
    }
    stages {
        stage('Setup') {
            steps {
                sh 'jenkins/scripts/setup.sh'
            }
        }
        stage('Test') {
            steps {
                sh 'jenkins/scripts/test.sh'
            }
        }
    }
}
